name:        Ammunition request
description: File a specific precious material ammunition request.
title:       "[ammo-request]: "
labels:      ["enhancement", "data", "ammo request"]
body:
  - type: markdown
    attributes:
      value: >-
        Please fill out the following form to request a specific precious
        material ammunition type. Note that we only support cold iron and silver
        ammunition at this time.
  - type: input
    id:   weapon-type
    attributes:
      label:       Weapon Type
      description: The type of weapon you want precious material ammunition for.
      placeholder: e.g. "Shortbow", "Repeating Heavy Crossbow", "Slide Pistol"
    validations:
      required: true
  - type: dropdown
    id:   material
    attributes:
      label:       Material
      description: The precious material you want the ammunition to be made of.
      options:
        - Cold Iron
        - Silver
    validations:
      required: true
  - type: input
    id:   reference
    attributes:
      label:       Reference
      description: A link to an authoritative reference for the weapon type. eg. Archives of Nethys.
      placeholder: e.g. https://2e.aonprd.com/Weapons.aspx?ID=160
    validations:
      required: false
