name: Prisha's Precious Projectiles CI

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update manifest
        id:   update-manifest
        run:  python ./.github/workflows/update-manifest.py ${{ github.ref_name }}
      - name: Zip files
        id:   zip-files
        run: |
          zip -r ./prishas-precious-projectiles.zip module.json packs README.md LICENSE
      - name: Create release
        id:   create-versioned-release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: false
          name:         Release ${{ github.ref_name }}
          draft:        false
          prerelease:   false
          token:        ${{ secrets.GITHUB_TOKEN }}
          artifacts:    "./module.json,./prishas-precious-projectiles.zip"
