name: Prisha's Precious Projectiles CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get version
        id:   get-version
        run:  echo "::set-output name=VERSION::$(node ./.github/workflows/get-version.js)"
      - name: Zip files
        run: |
          zip -r ./prishas-precious-projectiles.zip module.json packs README.md LICENSE
      - name: Create release
        id:   create-versioned-release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # set to false if you do not want to allow updates on existing releases
          name:         Release ${{ steps.get-version.outputs.VERSION }} # Use the version in the name
          draft:        false
          prerelease:   false
          token:        ${{ secrets.GITHUB_TOKEN }}
          artifacts:    "./module.json,./prishas-precious-projectiles.zip"
          tag:          ${{ steps.get-version.outputs.VERSION }}
