name: Prisha's Precious Projectiles CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check manifest
        id:   check-manifest
        run:  python ./.github/workflows/check-manifest.py
      - name: Get version
        id:   get-version
        run:  echo "VERSION=$(python ./.github/workflows/get-version.py)" >> $GITHUB_OUTPUT
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Build module
        run: npm run build
      - name: Zip files
        id:   zip-files
        run: |
          zip -r ./prishas-precious-projectiles.zip dist/module.json dist/packs README.md LICENSE
      - name: Create release
        id:   create-versioned-release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: false
          name:         Release ${{ steps.get-version.outputs.VERSION }}
          draft:        false
          prerelease:   false
          token:        ${{ secrets.GITHUB_TOKEN }}
          artifacts:    "./module.json,./prishas-precious-projectiles.zip"
          tag:          ${{ steps.get-version.outputs.VERSION }}
